# Primary Database Configuration
spring:
  primary:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/mydatabase
      username: postgres
      password: postgres

  # Secondary Database Configuration
  secondary:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/mydatabase
      username: postgres
      password: postgres